# Generated by Django 4.1 on 2022-08-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=100, unique=True, verbose_name='نام مستعار'),
            preserve_default=False,
        ),
    ]
