# Generated by Django 4.1 on 2022-08-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='floatfield',
            field=models.FloatField(default=1, verbose_name='مقدار عددی'),
        ),
    ]
